
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # THE PORT FORWARDING SEEMS TO NOT WORK, USE SSH
  #config.vm.network "forwarded_port", guest: 6379, host: 6379
  #config.vm.network "forwarded_port", guest: 5432, guest_ip: "127.0.0.1", host: 5432, host_ip: "127.0.0.1"
  #config.vm.network "forwarded_port", guest: 8000, guest_ip: "127.0.0.1", host: 8000, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  #config.vm.provision "shell", path: "bin/provision.sh", args: "password"
  # allow access as root
  config.vm.provision "shell", inline: "mkdir -p /root/.ssh && chmod 600 /root/.ssh && cp /home/vagrant/.ssh/authorized_keys /root/.ssh/"
end

